spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventory-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 0

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://discovery-server:8761/eureka

